:wrench: fix modulo operation for unsigned integer in the CppToken use of CppIntegerConstantEvaluator.
This fixes Boost Preprocessor iteration misinterpretation of the lower iteration bound, leading to errors like reverse iteration not being detected. ( Discovered with Boost Log that uses an undefined upper bound, which is correctly interpreted as zero, but lower bound that is 1 is interpreted as 0 too by goma, while should simply be 1).

```
In file included from /usr/local/share/.tipi/vL.w/f58d423-boost/libs/log/src/default_sink.cpp:27:
In file included from /usr/local/share/.tipi/vL.w/f58d423-boost/libs/log/src/default_sink.hpp:22:
In file included from /usr/local/share/.tipi/vL.w/f58d423-boost/libs/log/include/boost/log/attributes/value_extraction.hpp:39:
In file included from /usr/local/share/.tipi/vL.w/f58d423-boost/libs/log/include/boost/log/utility/value_ref.hpp:38:
In file included from /usr/local/share/.tipi/vL.w/f58d423-boost/libs/log/include/boost/log/detail/value_ref_visitation.hpp:71:
/usr/local/share/.tipi/vL.w/f58d423-boost/libs/preprocessor/include/boost/preprocessor/iteration/detail/iter/forward1.hpp:45:14: fatal error: 'boost/preprocessor/iteration/detail/iter/reverse1.hpp' file not found
   45 | #    include <boost/preprocessor/iteration/detail/iter/reverse1.hpp>
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

The problem is that goma when running BOOST_PP_SLOT_OFFSET_2 ( boost/preprocessor/slot/detail/shared.hpp ) , which expands to a modulo operation `1 % 1000000000UL % 100000000UL % 10000000UL % 1000000UL % 100000UL % 10000UL % 1000UL % 100UL % 10UL` which would yield 1, did run a division : `1 / 1000000000UL / 100000000UL / 10000000UL / 1000000UL / 100000UL / 10000UL / 1000UL / 100UL / 10U` which yields 0.

This results in the lower bound being defined to 0 and reverse1.hpp is not included, leading to differing required input tree from the compiler and from goma.

Fix tipi-build/specs-cmake-re#136